url: "https://atelier2d.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "atelier2d" # the subpath of your site, e.g. /blog
environment: production

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

markdown: kramdown


title: "Atelier 2D - Conception et Maitrise d'oeuvre à Langueux et Saint-Brieuc" # the name of your site, e.g. ACME Corp.
tagline: "Créativité et Expertise: Votre Vision, Notre Mission."
description: "Maître d'œuvre à Langueux, spécialistes en conception et suivi de travaux avec artisans locaux. Intervenant sur 35kms autour de Saint-Brieuc. Expertise RE2020, rénovation et extensions."
# logo: /assets/images/logoLSA.png
locale: "Fr"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

facebook:
  app_id: 61551899341644

social:
  links:
  - https://www.facebook.com/profile.php?id=61551899341644

