url: "https://atelier2d.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "atelier2d" # the subpath of your site, e.g. /blog
title: "Atelier 2D - Conception et Maîtrise d'Œuvre" # the name of your site, e.g. ACME Corp.

sass:
  sass_dir: _sass
  style: compact # possible values: nested expanded compact compressed

